version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./logs:/app/logs
    env_file:
      - backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.bot
    volumes:
      - ./telegram_bot/bot:/app/bot
      - ./logs:/app/logs
      - ./telegram_bot/folder_to_reports:/app/folder_to_reports
    env_file:
      - telegram_bot/.env
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: 