FROM python:3.12-slim

WORKDIR /backend

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY alembic .
COPY alembic.ini .
COPY ./app .
COPY .env .

COPY entrypoint.sh ./
RUN chmod +x entrypoint.sh

ENV PYTHONPATH=.

CMD ["./entrypoint.sh"]